##### 下面代码的输出是什么?
```
(() => {
  let x, y;
  try {
    throw new Error();
  } catch (x) {
    (x = 1), (y = 2);
    console.log(x);
  }
  console.log(x);
  console.log(y);
})();
```
答案：1 undefined 2  
**catch块接收参数x。当我们传递参数时，这与变量的x不同。这个变量x是属于catch作用域的。**   
在catch块之外，x仍然是undefined，而y是2  